/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    Card: typeof import('./theme/components/Card.vue')['default']
    ChatMessage: typeof import('./theme/components/ChatMessage.vue')['default']
    ChatPanel: typeof import('./theme/components/ChatPanel.vue')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    DataPanel: typeof import('./theme/components/DataPanel.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
  }
}
